application: tuquinielaca
version: 1-dev
runtime: python
api_version: 1

handlers:
- url: /.*
  script: main.py
  
- url: /remote_api  
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py  
  login: admin 
  
builtins:
- datastore_admin: on
- remote_api: on
